name: Domain Switch

on:
  push:
    paths:
      - 'bin/sethost'
      - 'etc/hostname*'
      - 'CNAME'
  schedule:
    - cron: '0 0 12 1 *'  # Schedule updated by sethost script
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  update-hostname:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run sethost script
        run: |
          chmod +x ./bin/sethost
          ./bin/sethost
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update hostname based on domain expiry"
          git push